from test.mock_data.mock_users import (
    none_user,
    bronze_user,
    silver_user,
    gold_user,
    platinum_user,
)

five_games = [
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
]
twelve_games = [
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
]
twenty_six_games = [
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
]
fifty_two_games = [
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
    {"id": 0, "title": "Game 1", "totalAvailableAchievements": 20},
]

none_lib = {"user": none_user, "ownedGames": five_games}
bronze_lib = {"user": bronze_user, "ownedGames": twelve_games}
silver_lib = {"user": silver_user, "ownedGames": twelve_games}
gold_lib = {"user": gold_user, "ownedGames": twenty_six_games}
platinum_lib = {"user": platinum_user, "ownedGames": fifty_two_games}
