name: Commit testing
run-name: ${{ github.actor }} has commited work to test
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ls -la ${{ github.workspace }}

      - name: Run unit tests
        run: python -m unitest ps-challenge